name: Jana_cicd_process

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'sf_scripts/**'
      
  workflow_dispatch:

jobs:
  snowflake-cicd:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
	with: 
	  python-version: 3.8.x
      - name: Run schemachange
        env: 
	SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
	SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_PRE }}
	SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_PRE }}
	SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASS_PRE }}
	SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH_PRE }}
	SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB_PRE }}

      # Runs a set of commands using the runners shell      
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE
	  python  --version
          echo "Step 1: Installing schemachange"
          pip install schemachange		  
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/sf_scripts - a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -p $SNOWFLAKE_PASSWORD -w $SNOWFLAKE_WH -d $SNOWFLAKE_DB
